// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ramiCohenCs.Models;

namespace ramiCohenCs.Migrations.Orders
{
    [DbContext(typeof(OrdersContext))]
    partial class OrdersContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.14-servicing-32113")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ramiCohenCs.Models.OrdersDetails", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("address")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<string>("delivery")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<string>("email")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<string>("fullName")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<string>("orderStatus")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<string>("order_numberOfUnits")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<string>("personalGreeting")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<int>("phonNumber")
                        .HasColumnType("int");

                    b.Property<string>("remarks")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<string>("totalPrice")
                        .IsRequired()
                        .HasColumnType("varchar(10)");

                    b.HasKey("id");

                    b.ToTable("orders");
                });
#pragma warning restore 612, 618
        }
    }
}
